# Copyright 2023 Chris Farris <chrisf@primeharbor.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Backup Vaults in every account & core regions

Parameters:

  pRoleName:
    Description: Name of the IAM Role to deploy in us-east-1 for the AWS Backup Service
    Type: String
    Default: CentralAWSBackupRole

  pVaultNamePrefix:
    Description: Prefix for the Backup Vault Name to be deployed in all Accounts
    Type: String
    Default: BCPVault

  pAWSOrgUnit:
    Description: AWS Organizations OU to deploy this stackset to. Probably should be the root OU
    Type: String
    AllowedPattern: '^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$'

Resources:

  VaultStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: True
        RetainStacksOnAccountRemoval: True
      CallAs: DELEGATED_ADMIN
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      Description: Organizational StackSet to Deploy AWS Backup Vaults
      OperationPreferences:
        # Per the docs: MaxConcurrentCount is at most one more than the FailureToleranceCount.
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
      Parameters:
        - ParameterKey: pRoleName
          ParameterValue: !Ref pRoleName
        - ParameterKey: pVaultNamePrefix
          ParameterValue: !Ref pVaultNamePrefix
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref pAWSOrgUnit
          Regions:
            - us-east-1
            - eu-north-1
            - ap-south-1
            - eu-west-3
            - eu-west-2
            - eu-west-1
            - ap-northeast-3
            - ap-northeast-2
            - ap-northeast-1
            - sa-east-1
            - ca-central-1
            - ap-southeast-1
            - ap-southeast-2
            - eu-central-1
            - us-east-2
            - us-west-1
            - us-west-2
      StackSetName: !Sub "${AWS::StackName}-StackSet"
      TemplateBody: |
          AWSTemplateFormatVersion: '2010-09-09'
          Description: Deploys AWS Backup Vaults for use with an Organizational Backup Policy.

          Parameters:

            pVaultNamePrefix:
              Description: Name of the Backup Vault to create
              Type: String

            pRoleName:
              Description: Name of the ServiceLinked Role to Create. **DO NOT CHANGE**
              Type: String

          Conditions:
            cCreateServiceLinkedRole: !Equals [ !Ref "AWS::Region", "us-east-1"]
            cCreateCrossRegionalVault: !Or [ !Equals [ !Ref "AWS::Region", "us-east-1"], !Equals [ !Ref "AWS::Region", "us-west-2"] ]

          Resources:

            RequiredServiceRole:
              Condition: cCreateServiceLinkedRole
              Type: "AWS::IAM::Role"
              Properties:
                RoleName: !Ref pRoleName
                AssumeRolePolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                    - Effect: "Allow"
                      Principal:
                        Service:
                          - "backup.amazonaws.com"
                      Action:
                        - "sts:AssumeRole"
                ManagedPolicyArns:
                  - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"

            Tier1Vault:
              Type: AWS::Backup::BackupVault
              Properties:
                # AccessPolicy: Json
                BackupVaultName: !Sub ${pVaultNamePrefix}-tier1
                BackupVaultTags:
                  deployed_by : Centrally Managed AWS Backup CloudFormation Stack.
                LockConfiguration:
                  # ChangeableForDays: Integer
                  MaxRetentionDays: 180
                  MinRetentionDays: 180

            Tier2Vault:
              Type: AWS::Backup::BackupVault
              Properties:
                # AccessPolicy: Json
                BackupVaultName: !Sub ${pVaultNamePrefix}-tier2
                BackupVaultTags:
                  deployed_by : Centrally Managed AWS Backup CloudFormation Stack.
                LockConfiguration:
                  # ChangeableForDays: Integer
                  MaxRetentionDays: 180
                  MinRetentionDays: 180

            Tier3Vault:
              Type: AWS::Backup::BackupVault
              Properties:
                # AccessPolicy: Json
                BackupVaultName: !Sub ${pVaultNamePrefix}-tier3
                BackupVaultTags:
                  deployed_by : Centrally Managed AWS Backup CloudFormation Stack.
                LockConfiguration:
                  # ChangeableForDays: Integer
                  MaxRetentionDays: 90
                  MinRetentionDays: 90

            Tier4Vault:
              Type: AWS::Backup::BackupVault
              Properties:
                # AccessPolicy: Json
                BackupVaultName: !Sub ${pVaultNamePrefix}-tier4
                BackupVaultTags:
                  deployed_by : Centrally Managed AWS Backup CloudFormation Stack.
                LockConfiguration:
                  # ChangeableForDays: Integer
                  MaxRetentionDays: 45
                  MinRetentionDays: 45

            CrossRegionalVault:
              Type: AWS::Backup::BackupVault
              Condition: cCreateCrossRegionalVault
              Properties:
                # AccessPolicy: Json
                BackupVaultName: !Sub ${pVaultNamePrefix}-CrossRegional-${AWS::Region}
                BackupVaultTags:
                  deployed_by : Centrally Managed AWS Backup CloudFormation Stack.
                LockConfiguration:
                  # ChangeableForDays: Integer
                  MaxRetentionDays: 180
                  MinRetentionDays: 180

          Outputs:
            TemplateVersion:
              Value: "1.0.1"

          ######## End of StackSet Instance Template

Outputs:

  TemplateVersion:
    Value: "1.0.0"
